<?php

/**
 * FormVitalOptions represents the measurement details for a specific vital sign in the system.
 * For backwards compatibility it extends ORDataObject (which implements the a form of the Active record data pattern),
 * but the preferred mechanism is to use this as a POPO (Plain old PHP object) and save / retrieve data using
 * the VitalsService class.
 * @package openemr
 * @link      http://www.open-emr.org
 * @author    Stephen Nielson <stephen@nielson.org>
 * @copyright Copyright (c) 2021 Stephen Nielson <stephen@nielson.org>
 * @license   https://github.com/openemr/openemr/blob/master/LICENSE GNU General Public License 3
 */

namespace OpenEMR\Common\Forms;

use OpenEMR\Common\ORDataObject\ORDataObject;

/**
 * Class FormVitalOptions
 */
class FormVitalOptions extends ORDataObject
{
    /**
     *
     * @access public
     */
    const TABLE_NAME = "form_vital_options";

    private $id;


    /**
     * @var number The unique id of the form (id column in form_vitals and form_id in the forms table).
     */
    private $form_id;

    /**
     * The unique id
     * @var string
     */
    private $uuid;

    /**
     * The name of the vitals column this detail pertains to
     * @var string
     */
    private $vitals_column;

    /**
     * Represents the list_options list id for the vitals vital_option
     * @var string
     */
    private $vital_option_list_id;


    /**
     * Represents the list_options option id for the vitals vital_option
     * @var string
     */
    private $vital_option_option_id;

    /**
     * @var string
     */
    private $vital_option_title;

    /**
     * @var string
     */
    private $vital_option_codes;

    public function __construct()
    {
        parent::__construct(self::TABLE_NAME);
    }

    public function persist()
    {
        return parent::persist(); // TODO: Change the autogenerated stub
    }

    /**
     * @return mixed
     */
    public function get_id()
    {
        return $this->id;
    }

    /**
     * @param mixed $id
     * @return FormVitalOptions
     */
    public function set_id($id)
    {
        $this->id = $id;
        return $this;
    }

    /**
     * @return string
     */
    public function get_uuid(): ?string
    {
        return $this->uuid;
    }

    /**
     * @param string $uuid
     * @return FormVitalOptions
     */
    public function set_uuid(string $uuid): FormVitalOptions
    {
        $this->uuid = $uuid;
        return $this;
    }

    /**
     * @return string
     */
    public function get_vitals_column(): ?string
    {
        return $this->vitals_column;
    }

    /**
     * @param string $vitals_column
     * @return FormVitalOptions
     */
    public function set_vitals_column(string $vitals_column): FormVitalOptions
    {
        $this->vitals_column = $vitals_column;
        return $this;
    }

    /**
     * @return string
     */
    public function get_vital_option_list_id(): ?string
    {
        return $this->vital_option_list_id;
    }

    /**
     * @param string $vital_option_list_id
     * @return FormVitalOptions
     */
    public function set_vital_option_list_id(string $vital_option_list_id): FormVitalOptions
    {
        $this->vital_option_list_id = $vital_option_list_id;
        return $this;
    }

    /**
     * @return string
     */
    public function get_vital_option_option_id(): ?string
    {
        return $this->vital_option_option_id;
    }

    /**
     * @param string $vital_option_option_id
     * @return FormVitalOptions
     */
    public function set_vital_option_option_id(string $vital_option_option_id): FormVitalOptions
    {
        $this->vital_option_option_id = $vital_option_option_id;
        return $this;
    }


    /**
     * @return string
     */
    public function get_vital_option_title(): ?string
    {
        return $this->vital_option_title;
    }

    /**
     * @param string $vital_option_title
     * @return FormVitalOptions
     */
    public function set_vital_option_title(string $vital_option_title): FormVitalOptions
    {
        $this->vital_option_title = $vital_option_title;
        return $this;
    }

    /**
     * @return string
     */
    public function get_vital_option_codes(): ?string
    {
        return $this->vital_option_codes;
    }

    /**
     * @param string $vital_option_code
     * @return FormVitalOptions
     */
    public function set_vital_option_codes(string $vital_option_codes): FormVitalOptions
    {
        $this->vital_option_codes = $vital_option_codes;
        return $this;
    }

    public function clear_vital_option()
    {
        $this->vital_option_codes = null;
        $this->vital_option_option_id = null;
        $this->vital_option_list_id = null;
        $this->vital_option_title = null;
    }

    public function set_form_id(?int $form_id)
    {
        $this->form_id = $form_id;
    }

    public function get_form_id(): ?int
    {
        return $this->form_id;
    }
}
